<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <RootNamespace>Demo.Application.Tests</RootNamespace>
    <AssemblyName>Demo.Application.Tests</AssemblyName>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\Demo.Application\Application.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
    <Using Include="NSubstitute" />
  </ItemGroup>

</Project>
